### PR TITLE
Dev/cjs/200519/clean master

### PR DESCRIPTION
**Pull request by 0cjs**
Stop mixing the ASL code into our local code and docs for importing ASL releases, which also means we no longer need ever to rebase the master branch. This cleanup and dropping master branch rebasing makes the repo less confusing.

Full details are in the commit messages below.

@KubaO I think that this is pretty clean and obvious, but I wanted to run this by you before actually bringing it on to `master`.

This also sets the stage for doing a cleaner import that requires less manual work. In particular, [`git-commit-filetree`](https://github.com/cynic-net/git-commit-filetree) could be used to directly put new imports on to the `upstream` branch without needing to check it out.

### CODE REVIEW

**Comment by KubaO** [comment]
Removing a branch is a simple ref delete. There's no need to push anything, in fact it's the opposite: just delete the branch from this repo. If you want to do other changes, do them in another branch - this one should vanish. Deleting the individual files is just noise - if this branch was used anywhere, then I presume it's a part of the history at point of use, and it won't really disappear (whether you delete the files or the ref). But branch removal should never involve actually deleting or modifying any files. Just the ref itself.

Feel free to add the README etc. changes to another branch, or master, or whatever works, and delete this one.

**Comment by 0cjs** [comment]
Ah, I see I left out some explanation that I'd meant to put in that commit removing the ASL files from master. I've added another paragraph to the commit message covering that:

> I also considered creating a new branch starting at the first commit and containing only the import code/doc commits, which would replace the current `master`, become the default branch (so the README shows on GitHub's top page for the repo), and probably keep the name `master`. However, it seemed to me better and less confusing to keep the current history rather than, for existing clones of the repo, a) forcing a rebase of the `master` branch or b) leaving them on a branch that no longer exists in the remote.

To be clear, I'm not trying to delete a branch; regardless of how we do this we come out with the same number of branches we started with. While it's possible to remove the current branch labeled `master` and add another branch (with the same or a different name), that seems to add complexity with no real benefit.

Here's my reasoning behind doing it the way I've proposed in this PR:
1. Every repo must have a default branch, which cannot be deleted.
2. This repo's default branch should be the one that contains our README about the import system so that that README is shown when people go to the repo's top page on GitHub.
3. There seems to be no good reason not to have a `master` branch which is the default branch, and leaving it that way follows a standard convention, helping to avoid confusion.
4. While preserving the current history of `master` does leave a lot of commits on it, I felt that preserving the history of how we used to do things is helpful enough (especially in explaining why certain things are done in `download.sh` and making it more clear what we can remove from it if we clean it up) was more valuable.

That said, I'm not wedded to point 4, so if you have a strong opinion that it's better to kill the history I'll cons up another PR that does it that way and we can compare the two. But I do think that `download.sh` will be clearer and easier to clean up at some point (especially if someone other than you or me does it), if that history is preserved.

**Comment by 0cjs** [comment]
@KubaO Did you have any further comments on this?

**Comment by KubaO** [comment]
No further comments. Feel free to merge. I re-added you to the repo, let me know that you have push access.

**Comment by KubaO** [comment]
There's a chat in the Dev team. You'll need to change the remote from KubaO/asl to asl-developers/asl to push/pull from it :)

**Comment by 0cjs** [comment]
> You'll need to change the remote from KubaO/asl to asl-developers/asl to push/pull from it :)

Actually, when you use GitHub facilities to move a repo (including changing the owner) it will automatically install forwarding for the old URL, at least until the old name is used for something else, so fetches from `KubaO/asl.git` continue to work for the moment. (I've just confirmed now that this is working.)

Thanks for the heads-up on all of this!

**Pull request merged**
